#!/usr/bin/env python3
"""Embed host/cube_control.html into the firmware as a PROGMEM string.

One source of truth: edit the HTML, re-run this, reflash. Keeps the page
the cube serves identical to the one you can open from disk.

    python3 tools/embed_html.py
"""

import pathlib
import re
import sys

ROOT = pathlib.Path(__file__).resolve().parent.parent
SRC = ROOT / "host" / "cube_control.html"
DST = ROOT / "firmware" / "ESPcube" / "webpage.h"

html = SRC.read_text()

# A C++ raw string ends at the delimiter, so it must not appear in the page.
DELIM = "cubehtml"
if f'){DELIM}"' in html:
    sys.exit(f"page contains the raw-string delimiter ){DELIM}\" — pick another")

# Trim what only matters on disk: comments and leading indentation. The
# ESP has ~1MB for the sketch, but there's no reason to spend it on
# whitespace.
html = re.sub(r"<!--.*?-->", "", html, flags=re.S)
html = "\n".join(line.rstrip() for line in html.splitlines() if line.strip())

DST.write_text(
    "// Generated by tools/embed_html.py — do not edit.\n"
    "// Source: host/cube_control.html\n"
    "#pragma once\n\n"
    f'const char kControlPage[] PROGMEM = R"{DELIM}(\n{html}\n){DELIM}";\n'
)

print(f"{SRC.name} -> {DST.relative_to(ROOT)}  ({len(html):,} bytes)")
